package com.github.kinoamyfx.tushare4j.finance;

import com.github.kinoamyfx.tushare4j.CodeUtils;

public class BalanceSheetTest {

    String content = "<tbody><tr>\n" +
            "<td>ts_code</td>\n" +
            "<td>str</td>\n" +
            "<td>TS股票代码</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ann_date</td>\n" +
            "<td>str</td>\n" +
            "<td>公告日期</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>f_ann_date</td>\n" +
            "<td>str</td>\n" +
            "<td>实际公告日期</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>end_date</td>\n" +
            "<td>str</td>\n" +
            "<td>报告期</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>report_type</td>\n" +
            "<td>str</td>\n" +
            "<td>报表类型：见下方详细说明</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>comp_type</td>\n" +
            "<td>str</td>\n" +
            "<td>公司类型：1一般工商业 2银行 3保险 4证券</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_share</td>\n" +
            "<td>float</td>\n" +
            "<td>期末总股本</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cap_rese</td>\n" +
            "<td>float</td>\n" +
            "<td>资本公积金 (元，下同)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>undistr_porfit</td>\n" +
            "<td>float</td>\n" +
            "<td>未分配利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>surplus_rese</td>\n" +
            "<td>float</td>\n" +
            "<td>盈余公积金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>special_rese</td>\n" +
            "<td>float</td>\n" +
            "<td>专项储备</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>money_cap</td>\n" +
            "<td>float</td>\n" +
            "<td>货币资金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>trad_asset</td>\n" +
            "<td>float</td>\n" +
            "<td>交易性金融资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>notes_receiv</td>\n" +
            "<td>float</td>\n" +
            "<td>应收票据</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>accounts_receiv</td>\n" +
            "<td>float</td>\n" +
            "<td>应收账款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_receiv</td>\n" +
            "<td>float</td>\n" +
            "<td>其他应收款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>prepayment</td>\n" +
            "<td>float</td>\n" +
            "<td>预付款项</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>div_receiv</td>\n" +
            "<td>float</td>\n" +
            "<td>应收股利</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>int_receiv</td>\n" +
            "<td>float</td>\n" +
            "<td>应收利息</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>inventories</td>\n" +
            "<td>float</td>\n" +
            "<td>存货</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>amor_exp</td>\n" +
            "<td>float</td>\n" +
            "<td>长期待摊费用</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>nca_within_1y</td>\n" +
            "<td>float</td>\n" +
            "<td>一年内到期的非流动资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>sett_rsrv</td>\n" +
            "<td>float</td>\n" +
            "<td>结算备付金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>loanto_oth_bank_fi</td>\n" +
            "<td>float</td>\n" +
            "<td>拆出资金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>premium_receiv</td>\n" +
            "<td>float</td>\n" +
            "<td>应收保费</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>reinsur_receiv</td>\n" +
            "<td>float</td>\n" +
            "<td>应收分保账款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>reinsur_res_receiv</td>\n" +
            "<td>float</td>\n" +
            "<td>应收分保合同准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>pur_resale_fa</td>\n" +
            "<td>float</td>\n" +
            "<td>买入返售金融资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_cur_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>其他流动资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_cur_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>流动资产合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>fa_avail_for_sale</td>\n" +
            "<td>float</td>\n" +
            "<td>可供出售金融资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>htm_invest</td>\n" +
            "<td>float</td>\n" +
            "<td>持有至到期投资</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>lt_eqt_invest</td>\n" +
            "<td>float</td>\n" +
            "<td>长期股权投资</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>invest_real_estate</td>\n" +
            "<td>float</td>\n" +
            "<td>投资性房地产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>time_deposits</td>\n" +
            "<td>float</td>\n" +
            "<td>定期存款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>其他资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>lt_rec</td>\n" +
            "<td>float</td>\n" +
            "<td>长期应收款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>fix_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>固定资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cip</td>\n" +
            "<td>float</td>\n" +
            "<td>在建工程</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>const_materials</td>\n" +
            "<td>float</td>\n" +
            "<td>工程物资</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>fixed_assets_disp</td>\n" +
            "<td>float</td>\n" +
            "<td>固定资产清理</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>produc_bio_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>生产性生物资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oil_and_gas_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>油气资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>intan_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>无形资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>r_and_d</td>\n" +
            "<td>float</td>\n" +
            "<td>研发支出</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>goodwill</td>\n" +
            "<td>float</td>\n" +
            "<td>商誉</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>lt_amor_exp</td>\n" +
            "<td>float</td>\n" +
            "<td>长期待摊费用</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>defer_tax_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>递延所得税资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>decr_in_disbur</td>\n" +
            "<td>float</td>\n" +
            "<td>发放贷款及垫款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_nca</td>\n" +
            "<td>float</td>\n" +
            "<td>其他非流动资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_nca</td>\n" +
            "<td>float</td>\n" +
            "<td>非流动资产合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cash_reser_cb</td>\n" +
            "<td>float</td>\n" +
            "<td>现金及存放中央银行款项</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>depos_in_oth_bfi</td>\n" +
            "<td>float</td>\n" +
            "<td>存放同业和其它金融机构款项</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>prec_metals</td>\n" +
            "<td>float</td>\n" +
            "<td>贵金属</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>deriv_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>衍生金融资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>rr_reins_une_prem</td>\n" +
            "<td>float</td>\n" +
            "<td>应收分保未到期责任准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>rr_reins_outstd_cla</td>\n" +
            "<td>float</td>\n" +
            "<td>应收分保未决赔款准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>rr_reins_lins_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>应收分保寿险责任准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>rr_reins_lthins_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>应收分保长期健康险责任准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>refund_depos</td>\n" +
            "<td>float</td>\n" +
            "<td>存出保证金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ph_pledge_loans</td>\n" +
            "<td>float</td>\n" +
            "<td>保户质押贷款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>refund_cap_depos</td>\n" +
            "<td>float</td>\n" +
            "<td>存出资本保证金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>indep_acct_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>独立账户资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>client_depos</td>\n" +
            "<td>float</td>\n" +
            "<td>其中：客户资金存款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>client_prov</td>\n" +
            "<td>float</td>\n" +
            "<td>其中：客户备付金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>transac_seat_fee</td>\n" +
            "<td>float</td>\n" +
            "<td>其中:交易席位费</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>invest_as_receiv</td>\n" +
            "<td>float</td>\n" +
            "<td>应收款项类投资</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>资产总计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>lt_borr</td>\n" +
            "<td>float</td>\n" +
            "<td>长期借款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>st_borr</td>\n" +
            "<td>float</td>\n" +
            "<td>短期借款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cb_borr</td>\n" +
            "<td>float</td>\n" +
            "<td>向中央银行借款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>depos_ib_deposits</td>\n" +
            "<td>float</td>\n" +
            "<td>吸收存款及同业存放</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>loan_oth_bank</td>\n" +
            "<td>float</td>\n" +
            "<td>拆入资金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>trading_fl</td>\n" +
            "<td>float</td>\n" +
            "<td>交易性金融负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>notes_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付票据</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>acct_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付账款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>adv_receipts</td>\n" +
            "<td>float</td>\n" +
            "<td>预收款项</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>sold_for_repur_fa</td>\n" +
            "<td>float</td>\n" +
            "<td>卖出回购金融资产款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>comm_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付手续费及佣金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>payroll_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付职工薪酬</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>taxes_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应交税费</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>int_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付利息</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>div_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付股利</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>其他应付款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>acc_exp</td>\n" +
            "<td>float</td>\n" +
            "<td>预提费用</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>deferred_inc</td>\n" +
            "<td>float</td>\n" +
            "<td>递延收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>st_bonds_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付短期债券</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>payable_to_reinsurer</td>\n" +
            "<td>float</td>\n" +
            "<td>应付分保账款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>rsrv_insur_cont</td>\n" +
            "<td>float</td>\n" +
            "<td>保险合同准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>acting_trading_sec</td>\n" +
            "<td>float</td>\n" +
            "<td>代理买卖证券款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>acting_uw_sec</td>\n" +
            "<td>float</td>\n" +
            "<td>代理承销证券款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>non_cur_liab_due_1y</td>\n" +
            "<td>float</td>\n" +
            "<td>一年内到期的非流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_cur_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>其他流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_cur_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>流动负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>bond_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付债券</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>lt_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>长期应付款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>specific_payables</td>\n" +
            "<td>float</td>\n" +
            "<td>专项应付款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>estimated_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>预计负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>defer_tax_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>递延所得税负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>defer_inc_non_cur_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>递延收益-非流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_ncl</td>\n" +
            "<td>float</td>\n" +
            "<td>其他非流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_ncl</td>\n" +
            "<td>float</td>\n" +
            "<td>非流动负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>depos_oth_bfi</td>\n" +
            "<td>float</td>\n" +
            "<td>同业和其它金融机构存放款项</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>deriv_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>衍生金融负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>depos</td>\n" +
            "<td>float</td>\n" +
            "<td>吸收存款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>agency_bus_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>代理业务负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>其他负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>prem_receiv_adva</td>\n" +
            "<td>float</td>\n" +
            "<td>预收保费</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>depos_received</td>\n" +
            "<td>float</td>\n" +
            "<td>存入保证金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ph_invest</td>\n" +
            "<td>float</td>\n" +
            "<td>保户储金及投资款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>reser_une_prem</td>\n" +
            "<td>float</td>\n" +
            "<td>未到期责任准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>reser_outstd_claims</td>\n" +
            "<td>float</td>\n" +
            "<td>未决赔款准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>reser_lins_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>寿险责任准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>reser_lthins_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>长期健康险责任准备金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>indept_acc_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>独立账户负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>pledge_borr</td>\n" +
            "<td>float</td>\n" +
            "<td>其中:质押借款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>indem_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付赔付款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>policy_div_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付保单红利</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_liab</td>\n" +
            "<td>float</td>\n" +
            "<td>负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>treasury_share</td>\n" +
            "<td>float</td>\n" +
            "<td>减:库存股</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ordin_risk_reser</td>\n" +
            "<td>float</td>\n" +
            "<td>一般风险准备</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>forex_differ</td>\n" +
            "<td>float</td>\n" +
            "<td>外币报表折算差额</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>invest_loss_unconf</td>\n" +
            "<td>float</td>\n" +
            "<td>未确认的投资损失</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>minority_int</td>\n" +
            "<td>float</td>\n" +
            "<td>少数股东权益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_hldr_eqy_exc_min_int</td>\n" +
            "<td>float</td>\n" +
            "<td>股东权益合计(不含少数股东权益)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_hldr_eqy_inc_min_int</td>\n" +
            "<td>float</td>\n" +
            "<td>股东权益合计(含少数股东权益)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_liab_hldr_eqy</td>\n" +
            "<td>float</td>\n" +
            "<td>负债及股东权益总计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>lt_payroll_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>长期应付职工薪酬</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_comp_income</td>\n" +
            "<td>float</td>\n" +
            "<td>其他综合收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_eqt_tools</td>\n" +
            "<td>float</td>\n" +
            "<td>其他权益工具</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>oth_eqt_tools_p_shr</td>\n" +
            "<td>float</td>\n" +
            "<td>其他权益工具(优先股)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>lending_funds</td>\n" +
            "<td>float</td>\n" +
            "<td>融出资金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>acc_receivable</td>\n" +
            "<td>float</td>\n" +
            "<td>应收款项</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>st_fin_payable</td>\n" +
            "<td>float</td>\n" +
            "<td>应付短期融资款</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>payables</td>\n" +
            "<td>float</td>\n" +
            "<td>应付款项</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>hfs_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>持有待售的资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>hfs_sales</td>\n" +
            "<td>float</td>\n" +
            "<td>持有待售的负债</td>\n" +
            "</tr>\n" +
            "</tbody>";


    public void testG() {
        CodeUtils.codeg3(content);
    }
}