package com.github.kinoamyfx.tushare4j.finance;

import com.github.kinoamyfx.tushare4j.CodeUtils;
import org.junit.Test;

public class FinanceIndicatorTest {
    String content = "<tbody><tr>\n" +
            "<td>ts_code</td>\n" +
            "<td>str</td>\n" +
            "<td>TS代码</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ann_date</td>\n" +
            "<td>str</td>\n" +
            "<td>公告日期</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>end_date</td>\n" +
            "<td>str</td>\n" +
            "<td>报告期</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>eps</td>\n" +
            "<td>float</td>\n" +
            "<td>基本每股收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>dt_eps</td>\n" +
            "<td>float</td>\n" +
            "<td>稀释每股收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>total_revenue_ps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股营业总收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>revenue_ps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股营业收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>capital_rese_ps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股资本公积</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>surplus_rese_ps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股盈余公积</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>undist_profit_ps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股未分配利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>extra_item</td>\n" +
            "<td>float</td>\n" +
            "<td>非经常性损益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>profit_dedt</td>\n" +
            "<td>float</td>\n" +
            "<td>扣除非经常性损益后的净利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>gross_margin</td>\n" +
            "<td>float</td>\n" +
            "<td>毛利</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>current_ratio</td>\n" +
            "<td>float</td>\n" +
            "<td>流动比率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>quick_ratio</td>\n" +
            "<td>float</td>\n" +
            "<td>速动比率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cash_ratio</td>\n" +
            "<td>float</td>\n" +
            "<td>保守速动比率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>invturn_days</td>\n" +
            "<td>float</td>\n" +
            "<td>存货周转天数</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>arturn_days</td>\n" +
            "<td>float</td>\n" +
            "<td>应收账款周转天数</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>inv_turn</td>\n" +
            "<td>float</td>\n" +
            "<td>存货周转率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ar_turn</td>\n" +
            "<td>float</td>\n" +
            "<td>应收账款周转率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ca_turn</td>\n" +
            "<td>float</td>\n" +
            "<td>流动资产周转率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>fa_turn</td>\n" +
            "<td>float</td>\n" +
            "<td>固定资产周转率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>assets_turn</td>\n" +
            "<td>float</td>\n" +
            "<td>总资产周转率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>op_income</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动净收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>valuechange_income</td>\n" +
            "<td>float</td>\n" +
            "<td>价值变动净收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>interst_income</td>\n" +
            "<td>float</td>\n" +
            "<td>利息费用</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>daa</td>\n" +
            "<td>float</td>\n" +
            "<td>折旧与摊销</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ebit</td>\n" +
            "<td>float</td>\n" +
            "<td>息税前利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ebitda</td>\n" +
            "<td>float</td>\n" +
            "<td>息税折旧摊销前利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>fcff</td>\n" +
            "<td>float</td>\n" +
            "<td>企业自由现金流量</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>fcfe</td>\n" +
            "<td>float</td>\n" +
            "<td>股权自由现金流量</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>current_exint</td>\n" +
            "<td>float</td>\n" +
            "<td>无息流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>noncurrent_exint</td>\n" +
            "<td>float</td>\n" +
            "<td>无息非流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>interestdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>带息债务</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>netdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>净债务</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>tangible_asset</td>\n" +
            "<td>float</td>\n" +
            "<td>有形资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>working_capital</td>\n" +
            "<td>float</td>\n" +
            "<td>营运资金</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>networking_capital</td>\n" +
            "<td>float</td>\n" +
            "<td>营运流动资本</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>invest_capital</td>\n" +
            "<td>float</td>\n" +
            "<td>全部投入资本</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>retained_earnings</td>\n" +
            "<td>float</td>\n" +
            "<td>留存收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>diluted2_eps</td>\n" +
            "<td>float</td>\n" +
            "<td>期末摊薄每股收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>bps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股净资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ocfps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股经营活动产生的现金流量净额</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>retainedps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股留存收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cfps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股现金流量净额</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ebit_ps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股息税前利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>fcff_ps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股企业自由现金流量</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>fcfe_ps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股股东自由现金流量</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>netprofit_margin</td>\n" +
            "<td>float</td>\n" +
            "<td>销售净利率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>grossprofit_margin</td>\n" +
            "<td>float</td>\n" +
            "<td>销售毛利率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cogs_of_sales</td>\n" +
            "<td>float</td>\n" +
            "<td>销售成本率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>expense_of_sales</td>\n" +
            "<td>float</td>\n" +
            "<td>销售期间费用率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>profit_to_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>净利润/营业总收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>saleexp_to_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>销售费用/营业总收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>adminexp_of_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>管理费用/营业总收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>finaexp_of_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>财务费用/营业总收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>impai_ttm</td>\n" +
            "<td>float</td>\n" +
            "<td>资产减值损失/营业总收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>gc_of_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>营业总成本/营业总收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>op_of_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>营业利润/营业总收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ebit_of_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>息税前利润/营业总收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roe</td>\n" +
            "<td>float</td>\n" +
            "<td>净资产收益率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roe_waa</td>\n" +
            "<td>float</td>\n" +
            "<td>加权平均净资产收益率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roe_dt</td>\n" +
            "<td>float</td>\n" +
            "<td>净资产收益率(扣除非经常损益)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roa</td>\n" +
            "<td>float</td>\n" +
            "<td>总资产报酬率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>npta</td>\n" +
            "<td>float</td>\n" +
            "<td>总资产净利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roic</td>\n" +
            "<td>float</td>\n" +
            "<td>投入资本回报率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roe_yearly</td>\n" +
            "<td>float</td>\n" +
            "<td>年化净资产收益率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roa2_yearly</td>\n" +
            "<td>float</td>\n" +
            "<td>年化总资产报酬率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roe_avg</td>\n" +
            "<td>float</td>\n" +
            "<td>平均净资产收益率(增发条件)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>opincome_of_ebt</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动净收益/利润总额</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>investincome_of_ebt</td>\n" +
            "<td>float</td>\n" +
            "<td>价值变动净收益/利润总额</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>n_op_profit_of_ebt</td>\n" +
            "<td>float</td>\n" +
            "<td>营业外收支净额/利润总额</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>tax_to_ebt</td>\n" +
            "<td>float</td>\n" +
            "<td>所得税/利润总额</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>dtprofit_to_profit</td>\n" +
            "<td>float</td>\n" +
            "<td>扣除非经常损益后的净利润/净利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>salescash_to_or</td>\n" +
            "<td>float</td>\n" +
            "<td>销售商品提供劳务收到的现金/营业收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ocf_to_or</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额/营业收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ocf_to_opincome</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额/经营活动净收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>capitalized_to_da</td>\n" +
            "<td>float</td>\n" +
            "<td>资本支出/折旧和摊销</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>debt_to_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>资产负债率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>assets_to_eqt</td>\n" +
            "<td>float</td>\n" +
            "<td>权益乘数</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>dp_assets_to_eqt</td>\n" +
            "<td>float</td>\n" +
            "<td>权益乘数(杜邦分析)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ca_to_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>流动资产/总资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>nca_to_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>非流动资产/总资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>tbassets_to_totalassets</td>\n" +
            "<td>float</td>\n" +
            "<td>有形资产/总资产</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>int_to_talcap</td>\n" +
            "<td>float</td>\n" +
            "<td>带息债务/全部投入资本</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>eqt_to_talcapital</td>\n" +
            "<td>float</td>\n" +
            "<td>归属于母公司的股东权益/全部投入资本</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>currentdebt_to_debt</td>\n" +
            "<td>float</td>\n" +
            "<td>流动负债/负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>longdeb_to_debt</td>\n" +
            "<td>float</td>\n" +
            "<td>非流动负债/负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ocf_to_shortdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额/流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>debt_to_eqt</td>\n" +
            "<td>float</td>\n" +
            "<td>产权比率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>eqt_to_debt</td>\n" +
            "<td>float</td>\n" +
            "<td>归属于母公司的股东权益/负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>eqt_to_interestdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>归属于母公司的股东权益/带息债务</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>tangibleasset_to_debt</td>\n" +
            "<td>float</td>\n" +
            "<td>有形资产/负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>tangasset_to_intdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>有形资产/带息债务</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>tangibleasset_to_netdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>有形资产/净债务</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ocf_to_debt</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额/负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ocf_to_interestdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额/带息债务</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ocf_to_netdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额/净债务</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ebit_to_interest</td>\n" +
            "<td>float</td>\n" +
            "<td>已获利息倍数(EBIT/利息费用)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>longdebt_to_workingcapital</td>\n" +
            "<td>float</td>\n" +
            "<td>长期债务与营运资金比率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ebitda_to_debt</td>\n" +
            "<td>float</td>\n" +
            "<td>息税折旧摊销前利润/负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>turn_days</td>\n" +
            "<td>float</td>\n" +
            "<td>营业周期</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roa_yearly</td>\n" +
            "<td>float</td>\n" +
            "<td>年化总资产净利率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roa_dp</td>\n" +
            "<td>float</td>\n" +
            "<td>总资产净利率(杜邦分析)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>fixed_assets</td>\n" +
            "<td>float</td>\n" +
            "<td>固定资产合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>profit_prefin_exp</td>\n" +
            "<td>float</td>\n" +
            "<td>扣除财务费用前营业利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>non_op_profit</td>\n" +
            "<td>float</td>\n" +
            "<td>非营业利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>op_to_ebt</td>\n" +
            "<td>float</td>\n" +
            "<td>营业利润／利润总额</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>nop_to_ebt</td>\n" +
            "<td>float</td>\n" +
            "<td>非营业利润／利润总额</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ocf_to_profit</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额／营业利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cash_to_liqdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>货币资金／流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cash_to_liqdebt_withinterest</td>\n" +
            "<td>float</td>\n" +
            "<td>货币资金／带息流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>op_to_liqdebt</td>\n" +
            "<td>float</td>\n" +
            "<td>营业利润／流动负债</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>op_to_debt</td>\n" +
            "<td>float</td>\n" +
            "<td>营业利润／负债合计</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roic_yearly</td>\n" +
            "<td>float</td>\n" +
            "<td>年化投入资本回报率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>profit_to_op</td>\n" +
            "<td>float</td>\n" +
            "<td>利润总额／营业收入</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_opincome</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动单季度净收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_investincome</td>\n" +
            "<td>float</td>\n" +
            "<td>价值变动单季度净收益</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_dtprofit</td>\n" +
            "<td>float</td>\n" +
            "<td>扣除非经常损益后的单季度净利润</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_eps</td>\n" +
            "<td>float</td>\n" +
            "<td>每股收益(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_netprofit_margin</td>\n" +
            "<td>float</td>\n" +
            "<td>销售净利率(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_gsprofit_margin</td>\n" +
            "<td>float</td>\n" +
            "<td>销售毛利率(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_exp_to_sales</td>\n" +
            "<td>float</td>\n" +
            "<td>销售期间费用率(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_profit_to_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>净利润／营业总收入(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_saleexp_to_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>销售费用／营业总收入 (单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_adminexp_to_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>管理费用／营业总收入 (单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_finaexp_to_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>财务费用／营业总收入 (单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_impair_to_gr_ttm</td>\n" +
            "<td>float</td>\n" +
            "<td>资产减值损失／营业总收入(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_gc_to_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>营业总成本／营业总收入 (单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_op_to_gr</td>\n" +
            "<td>float</td>\n" +
            "<td>营业利润／营业总收入(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_roe</td>\n" +
            "<td>float</td>\n" +
            "<td>净资产收益率(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_dt_roe</td>\n" +
            "<td>float</td>\n" +
            "<td>净资产单季度收益率(扣除非经常损益)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_npta</td>\n" +
            "<td>float</td>\n" +
            "<td>总资产净利润(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_opincome_to_ebt</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动净收益／利润总额(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_investincome_to_ebt</td>\n" +
            "<td>float</td>\n" +
            "<td>价值变动净收益／利润总额(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_dtprofit_to_profit</td>\n" +
            "<td>float</td>\n" +
            "<td>扣除非经常损益后的净利润／净利润(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_salescash_to_or</td>\n" +
            "<td>float</td>\n" +
            "<td>销售商品提供劳务收到的现金／营业收入(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_ocf_to_sales</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额／营业收入(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_ocf_to_or</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额／经营活动净收益(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>basic_eps_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>基本每股收益同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>dt_eps_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>稀释每股收益同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>cfps_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>每股经营活动产生的现金流量净额同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>op_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>营业利润同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ebt_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>利润总额同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>netprofit_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>归属母公司股东的净利润同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>dt_netprofit_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>归属母公司股东的净利润-扣除非经常损益同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>ocf_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>经营活动产生的现金流量净额同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>roe_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>净资产收益率(摊薄)同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>bps_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>每股净资产相对年初增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>assets_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>资产总计相对年初增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>eqt_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>归属母公司的股东权益相对年初增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>tr_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>营业总收入同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>or_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>营业收入同比增长率(%)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_gr_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>营业总收入同比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_gr_qoq</td>\n" +
            "<td>float</td>\n" +
            "<td>营业总收入环比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_sales_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>营业收入同比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_sales_qoq</td>\n" +
            "<td>float</td>\n" +
            "<td>营业收入环比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_op_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>营业利润同比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_op_qoq</td>\n" +
            "<td>float</td>\n" +
            "<td>营业利润环比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_profit_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>净利润同比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_profit_qoq</td>\n" +
            "<td>float</td>\n" +
            "<td>净利润环比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_netprofit_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>归属母公司股东的净利润同比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>q_netprofit_qoq</td>\n" +
            "<td>float</td>\n" +
            "<td>归属母公司股东的净利润环比增长率(%)(单季度)</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>equity_yoy</td>\n" +
            "<td>float</td>\n" +
            "<td>净资产同比增长率</td>\n" +
            "</tr>\n" +
            "<tr>\n" +
            "<td>rd_exp</td>\n" +
            "<td>float</td>\n" +
            "<td>研发费用</td>\n" +
            "</tr>\n" +
            "</tbody>";

    @Test
    public void codeg() {
        CodeUtils.codeg3(content);
    }
}